/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SelectionDialog.java
 *
 * Created on Sep 13, 2010, 9:38:06 PM
 */

package org.smallutil.dialog;

import javax.swing.AbstractListModel;

/**
 *
 * @author MUFEED
 */
public class SelectionDialog<T> extends javax.swing.JDialog {
    boolean ok = false;
    
    /** Creates new form SelectionDialog */
    public SelectionDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList = new javax.swing.JList();
        jOK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList);

        jOK.setText("OK");
        jOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOKActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                    .add(jOK))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jOK)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOKActionPerformed
        setVisible(ok);
        ok = true;
    }//GEN-LAST:event_jOKActionPerformed

    public int getSelectionMode() {
        return jList.getSelectionMode();
    }

    public void setSelectionMode(int selectionMode) {
        jList.setSelectionMode(selectionMode);
    }
    
    public void setModel(final T[] data) {
        jList.setModel(new AbstractListModel() {
            T[] items = data;
            public int getSize() {
                return data.length;
            }

            public T getElementAt(int i) {
                return data[i];
            }
        });
    }

    public boolean isOk() {
        return ok;
    }
    
    public T[] getSelection() {
        int length = jList.getSelectedValues().length;
        T[] rVal = (T[]) new Object[length];
        for(int i = 0; i < length; i++)
          rVal[i] = (T) jList.getSelectedValues()[i];
        return rVal;
    }
    
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SelectionDialog<String> dialog = new SelectionDialog<String>(
                        new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                String[] data = {"item 1", "item 2", "item 3", "item 4", "item 5"};
                dialog.setModel(data);
                
                dialog.setVisible(true);

                if(dialog.isOk()) {
                    System.out.println("Selectoin: ");
                    Object[] sel = dialog.getSelection();
                    for(int i = 0; i < sel.length; i++)
                        System.out.println("\t" + sel[i]);
                }

                System.exit(0);

            }
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList jList;
    private javax.swing.JButton jOK;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
